#!/usr/bin/env python3

"""
Order Timing Analysis - When to Place Orders
"""

from datetime import datetime

def analyze_order_timing():
    """Analyze whether to place orders now or wait"""
    
    print("=" * 70)
    print("🕐 ORDER TIMING ANALYSIS")
    print("=" * 70)
    print(f"Current Time: {datetime.now().strftime('%I:%M %p PST')}")
    print("Market Status: CLOSED (opens 6:30 AM PST)")
    print()
    
    print("📊 CURRENT PRICES (from Alpha Vantage):")
    print("-" * 50)
    print("TDUP: $10.51")
    print("FUBO: $3.77")
    print()
    
    print("🎯 YOUR ORDER PLAN:")
    print("-" * 50)
    print("ENTRY ORDERS (To Buy):")
    print("  TDUP: Limit Buy @ $10.40 (15 shares)")
    print("  FUBO: Limit Buy @ $3.70 (44 shares)")
    print()
    print("EXIT TARGETS (To Sell - AFTER you own them):")
    print("  TDUP: Target $13.00 (+25% profit)")
    print("  FUBO: Target $5.00 (+35% profit)")
    print()
    
    print("=" * 70)
    print("⚠️ IMPORTANT DISTINCTION:")
    print("=" * 70)
    print()
    print("LIMIT BUY ORDERS (What you set tomorrow):")
    print("  • These are ENTRY prices")
    print("  • Set BELOW current price to get better entry")
    print("  • TDUP @ $10.40 (saves $0.11/share)")
    print("  • FUBO @ $3.70 (saves $0.07/share)")
    print()
    print("TARGET PRICES (NOT orders - just goals):")
    print("  • These are EXIT goals for AFTER you own shares")
    print("  • You DON'T place these as orders now")
    print("  • Monitor and sell manually when reached")
    print("  • Or set limit sells AFTER you own the shares")
    print()
    
    print("=" * 70)
    print("📱 SHOULD YOU PLACE ORDERS NOW?")
    print("=" * 70)
    print()
    print("✅ YES - You can place them now as:")
    print("  • 'Good Till Cancelled' (GTC) orders")
    print("  • They'll stay active until filled or you cancel")
    print("  • Set tonight, wake up to potential fills")
    print()
    print("⚠️ CONSIDERATIONS:")
    print("  • Pre-market starts at 4:00 AM PST")
    print("  • Stocks might gap up/down at open")
    print("  • Your limits might not fill if prices rise")
    print("  • But protects from overpaying")
    print()
    
    print("=" * 70)
    print("💡 RECOMMENDATION:")
    print("=" * 70)
    print()
    print("OPTION A: Place GTC Orders Tonight")
    print("-" * 50)
    print("1. Log into CIBC now")
    print("2. Place both orders as GTC (Good Till Cancelled)")
    print("3. Wake up and check if filled")
    print("4. If filled, set stop losses immediately")
    print()
    print("OPTION B: Wait for Morning")
    print("-" * 50)
    print("1. Wake at 6:25 AM PST")
    print("2. Check pre-market prices")
    print("3. Adjust limits if needed")
    print("4. Place as DAY orders")
    print()
    print("MY SUGGESTION: Option A (GTC tonight)")
    print("  • Removes emotion from morning")
    print("  • Ensures you don't oversleep")
    print("  • Limits protect from overpaying")
    print("  • Can always cancel if you change mind")
    print()
    
    print("=" * 70)
    print("⚠️ CRITICAL REMINDERS:")
    print("=" * 70)
    print("1. These are BUY orders, not sell targets")
    print("2. $13 and $5 are future profit targets")
    print("3. Set stop losses if orders fill")
    print("4. Don't forget existing position stops!")
    print("=" * 70)

if __name__ == "__main__":
    analyze_order_timing()