#!/usr/bin/env python3

"""
RBLX Put Options Comparison
Monthly vs January expiration analysis
"""

from datetime import datetime, timedelta

def compare_put_strategies():
    """Compare different put option strategies for RBLX"""
    
    print("=" * 70)
    print("💰 RBLX PUT OPTIONS - PROFIT COMPARISON")
    print("=" * 70)
    print(f"Time: {datetime.now().strftime('%I:%M %p PST')}")
    print(f"RBLX Current Price: $126.78")
    print()
    
    # Option data (estimates based on IV)
    monthly_exp = (datetime.now() + timedelta(days=31)).strftime('%b %d')
    january_exp = "Jan 16, 2026"
    
    print("=" * 70)
    print("📊 SINGLE PUT COMPARISON:")
    print("=" * 70)
    print()
    
    print("1️⃣ MONTHLY $125 PUT (Sep 14)")
    print("-" * 50)
    print("Cost: $4.00 x 100 = $400 per contract")
    print("Break-even: $121.00")
    print()
    print("PROFIT SCENARIOS (1 contract):")
    print("  RBLX → $120: +$100")
    print("  RBLX → $115: +$600") 
    print("  RBLX → $110: +$1,100")
    print("  RBLX → $100: +$2,100")
    print("  RBLX → $90:  +$3,100")
    print()
    print("WITH 2 CONTRACTS ($800 cost):")
    print("  RBLX → $110: +$2,200")
    print("  RBLX → $100: +$4,200")
    print("  RBLX → $90:  +$6,200")
    print()
    
    print("2️⃣ JANUARY $125 PUT (Jan 16, 2026)")
    print("-" * 50)
    print("Cost: ~$12.00 x 100 = $1,200 per contract")
    print("Break-even: $113.00")
    print()
    print("PROFIT SCENARIOS (1 contract):")
    print("  RBLX → $120: -$700 (still losing)")
    print("  RBLX → $115: -$200 (still losing)")
    print("  RBLX → $110: +$300")
    print("  RBLX → $100: +$1,300")
    print("  RBLX → $90:  +$2,300")
    print()
    
    print("=" * 70)
    print("🎯 PUT SPREAD COMPARISON:")
    print("=" * 70)
    print()
    
    print("3️⃣ MONTHLY PUT SPREAD (Recommended)")
    print("-" * 50)
    print("BUY:  2x $125 Put @ $4.00 = -$800")
    print("SELL: 2x $115 Put @ $1.50 = +$300")
    print("Net Cost: $500")
    print()
    print("PROFIT SCENARIOS:")
    print("  RBLX → $122.50: Break-even")
    print("  RBLX → $120: +$500")
    print("  RBLX → $115 or below: +$1,500 (MAX)")
    print()
    print("CAPPED at $1,500 but only risking $500!")
    print()
    
    print("4️⃣ AGGRESSIVE MONTHLY (More contracts)")
    print("-" * 50)
    print("BUY: 3x $125 Put @ $4.00 = $1,200")
    print()
    print("PROFIT SCENARIOS:")
    print("  RBLX → $120: +$300")
    print("  RBLX → $115: +$1,800")
    print("  RBLX → $110: +$3,300")
    print("  RBLX → $100: +$6,300")
    print("  RBLX → $90:  +$9,300")
    print()
    
    print("=" * 70)
    print("⏰ TIME VALUE COMPARISON:")
    print("=" * 70)
    print()
    
    print("MONTHLY (31 days):")
    print("• Theta decay: -$6/day")
    print("• Need move within 4 weeks")
    print("• Clear win/loss quickly")
    print("• Can redeploy capital if wrong")
    print()
    
    print("JANUARY (5 months):")
    print("• Theta decay: -$2/day (slower)")
    print("• More time for thesis to play out")
    print("• Capital locked up longer")
    print("• Higher premium cost upfront")
    print()
    
    print("=" * 70)
    print("💡 ANALYSIS: WHY MONTHLY IS BETTER HERE")
    print("=" * 70)
    print()
    
    print("1. NEWS-DRIVEN EVENT:")
    print("   • Class action news will impact quickly")
    print("   • Won't take 5 months to play out")
    print("   • Either happens in weeks or it's false")
    print()
    
    print("2. CAPITAL EFFICIENCY:")
    print("   • Monthly: Risk $800, make up to $6,200")
    print("   • January: Risk $1,200, make up to $2,300")
    print("   • Better return on capital with monthly")
    print()
    
    print("3. LOWER BREAK-EVEN:")
    print("   • Monthly: Profitable below $121")
    print("   • January: Need below $113 to profit")
    print("   • Easier to hit monthly target")
    print()
    
    print("4. QUICK FEEDBACK:")
    print("   • Know within month if thesis correct")
    print("   • Can redeploy capital if wrong")
    print("   • Not stuck waiting 5 months")
    print()
    
    print("=" * 70)
    print("🎯 MY RECOMMENDATIONS (RANKED):")
    print("=" * 70)
    print()
    
    print("OPTION A: SAFE PUT SPREAD ⭐⭐⭐⭐⭐")
    print("-" * 50)
    print("Buy 2x $125 Put, Sell 2x $115 Put (Monthly)")
    print("Cost: $500")
    print("Max Profit: $1,500")
    print("Risk/Reward: 3:1")
    print("Why: Best risk/reward, IV protected")
    print()
    
    print("OPTION B: AGGRESSIVE MONTHLY ⭐⭐⭐⭐")
    print("-" * 50)
    print("Buy 3x $125 Put (Monthly)")
    print("Cost: $1,200")
    print("Potential: $6,300 if drops to $100")
    print("Risk/Reward: 5:1")
    print("Why: Bigger upside, still reasonable time")
    print()
    
    print("OPTION C: CONSERVATIVE MONTHLY ⭐⭐⭐")
    print("-" * 50)
    print("Buy 2x $125 Put (Monthly)")
    print("Cost: $800")
    print("Potential: $4,200 if drops to $100")
    print("Risk/Reward: 5:1")
    print("Why: Good balance of risk/reward")
    print()
    
    print("OPTION D: JANUARY PUT ⭐⭐")
    print("-" * 50)
    print("Buy 1x $125 Put (Jan 2026)")
    print("Cost: $1,200")
    print("Potential: $2,300 if drops to $90")
    print("Risk/Reward: 2:1")
    print("Why: Only if you think it's a slow burn")
    print()
    
    print("=" * 70)
    print("✅ FINAL VERDICT:")
    print("=" * 70)
    print()
    print("GO WITH MONTHLY OPTIONS!")
    print()
    print("If you want $1,500 profit → Do the put spread")
    print("If you want $6,000+ potential → Buy 3x monthly puts")
    print()
    print("The January put is too expensive and ties up")
    print("capital for too long on a news-driven event.")
    print()
    print("News will either be confirmed/denied within weeks,")
    print("not months. Take the monthly and redeploy if wrong!")
    print("=" * 70)

if __name__ == "__main__":
    compare_put_strategies()