#!/usr/bin/env python3

"""
RBLX Safe Put Spread - Conservative Execution Plan
Risk $500 to make $1,500 with defined risk
"""

from datetime import datetime, timedelta

def safe_put_spread_plan():
    """Detailed plan for safe RBLX put spread"""
    
    print("=" * 70)
    print("🛡️ RBLX SAFE PUT SPREAD - EXECUTION PLAN")
    print("=" * 70)
    print(f"Time: {datetime.now().strftime('%I:%M %p PST')}")
    print("Strategy: CONSERVATIVE with DEFINED RISK")
    print()
    
    current_price = 126.78
    
    print("📊 THE SAFE TRADE STRUCTURE:")
    print("-" * 50)
    print("BUY:  2x RBLX $125 Put (Monthly)")
    print("SELL: 2x RBLX $115 Put (Monthly)")
    print(f"Expiration: {(datetime.now() + timedelta(days=31)).strftime('%B %d, %Y')}")
    print()
    
    print("💰 COST BREAKDOWN:")
    print("-" * 50)
    print("Buy 2x $125 Put @ $4.00 = -$800")
    print("Sell 2x $115 Put @ $1.50 = +$300")
    print("NET COST: $500")
    print()
    print("MAXIMUM RISK: $500 (can't lose more!)")
    print("MAXIMUM PROFIT: $1,500 (3x return)")
    print()
    
    print("=" * 70)
    print("📈 PROFIT SCENARIOS:")
    print("=" * 70)
    print()
    print(f"Current RBLX: ${current_price:.2f}")
    print()
    print("RBLX Price    | Your Profit/Loss")
    print("-" * 35)
    print("$130         | -$500 (max loss)")
    print("$125         | -$500 (max loss)")
    print("$122.50      | $0 (break-even)")
    print("$120         | +$500")
    print("$117.50      | +$1,000")
    print("$115 or less | +$1,500 (max profit)")
    print()
    
    print("=" * 70)
    print("🎯 WHY THIS IS SAFE:")
    print("=" * 70)
    print()
    print("1. DEFINED RISK:")
    print("   • Can only lose $500 maximum")
    print("   • No unlimited loss like shorting")
    print("   • Sleep well at night")
    print()
    print("2. IV CRUSH PROTECTION:")
    print("   • Selling $115 puts hedges volatility")
    print("   • If IV drops, both legs affected")
    print("   • Net impact minimized")
    print()
    print("3. REASONABLE TARGET:")
    print("   • Only need 3.5% drop to break-even")
    print("   • 9% drop for max profit")
    print("   • Not betting on total collapse")
    print()
    print("4. TIME TO WORK:")
    print("   • 31 days for thesis to play out")
    print("   • Not a weekly gamble")
    print("   • Can exit early if profitable")
    print()
    
    print("=" * 70)
    print("📋 EXECUTION CHECKLIST:")
    print("=" * 70)
    print()
    print("BEFORE PLACING TRADE:")
    print("□ Check RBLX is still around $126-127")
    print("□ Verify spread prices (~$2.50 net debit)")
    print("□ Confirm monthly expiration (not weekly)")
    print("□ Check bid-ask spreads are reasonable")
    print()
    print("ORDER ENTRY:")
    print("□ Enter as a SPREAD order (not separate)")
    print("□ Use LIMIT order at $2.50 debit")
    print("□ If not filled, adjust by $0.05")
    print("□ Don't chase if spread widens past $2.75")
    print()
    
    print("=" * 70)
    print("⏰ MANAGEMENT PLAN:")
    print("=" * 70)
    print()
    print("PROFIT TARGETS:")
    print("• At +$500 (RBLX $120): Consider taking 50% off")
    print("• At +$1,000 (RBLX $117.50): Take another 25% off")
    print("• Let final 25% ride for max profit")
    print()
    print("STOP LOSS RULES:")
    print("• If news debunked: EXIT immediately")
    print("• If RBLX rises above $130: EXIT")
    print("• After 2 weeks with no move: Reduce by 50%")
    print()
    print("TIME DECAY MANAGEMENT:")
    print("• Week 1-2: Hold full position")
    print("• Week 3: Reduce if no movement")
    print("• Week 4: Exit or roll to next month")
    print("• NEVER hold to expiration day")
    print()
    
    print("=" * 70)
    print("📱 MONITORING ALERTS:")
    print("=" * 70)
    print()
    print("Set these price alerts on RBLX:")
    print("• $125.00 - Approaching profit zone")
    print("• $122.50 - Break-even reached")
    print("• $120.00 - First profit target")
    print("• $115.00 - Maximum profit zone")
    print("• $130.00 - Warning (consider exit)")
    print()
    
    print("=" * 70)
    print("💡 ALTERNATIVE (EVEN SAFER):")
    print("=" * 70)
    print()
    print("If $500 feels like too much risk:")
    print()
    print("MINI SPREAD (1 contract each):")
    print("BUY:  1x $125 Put = -$400")
    print("SELL: 1x $115 Put = +$150")
    print("Net Cost: $250")
    print("Max Profit: $750")
    print("Still 3:1 reward/risk!")
    print()
    
    print("=" * 70)
    print("✅ FINAL SAFETY CHECKS:")
    print("=" * 70)
    print()
    print("✓ Maximum loss is limited to $500")
    print("✓ No margin required")
    print("✓ No unlimited risk")
    print("✓ Protected from IV crush")
    print("✓ 3:1 reward to risk ratio")
    print("✓ Only need small move to profit")
    print()
    print("This is as SAFE as betting against RBLX gets!")
    print()
    print("Ready to place the order? Enter as:")
    print('BUY 2 RBLX SEP125/115 PUT SPREAD @ $2.50 DEBIT')
    print("=" * 70)

if __name__ == "__main__":
    safe_put_spread_plan()